import { jules } from '@google/jules-sdk';

/**
 * Stitch Integration Example
 *
 * Demonstrates a workflow that uses Jules with Stitch.
 * This example simulates taking an AI-generated design description from Stitch
 * and asking an agent to convert it into a fully functional web component (React).
 */
async function main() {
  // Ensure the JULES_API_KEY environment variable is set.
  if (!process.env.JULES_API_KEY) {
    console.error('Error: JULES_API_KEY environment variable is not set.');
    console.error('Please set it using: export JULES_API_KEY="your-api-key"');
    process.exit(1);
  }

  console.log('Starting Stitch Integration Example...');

  // Simulated Stitch design prompt
  const stitchDesignContext = `
    Design Name: Hero Section
    Visual Description: A full-width hero section with a dark theme. It features a bold headline in the center, a subheadline below it, and two buttons (Primary: "Get Started", Secondary: "Learn More").
    Layout: Flexbox, centered items, padding top and bottom 5rem.
    Colors: Background #111827, Text #F9FAFB, Primary Button #3B82F6, Secondary Button transparent with #3B82F6 border.
  `;

  console.log('Sending design context to Jules session...');

  try {
    // 1. Create a session using the design context
    // We request the agent to output the code into a specific file so we can parse it.
    const session = await jules.session({
      prompt: `You are a frontend developer expert. Take the following design context generated by Stitch and convert it into a functional React component using Tailwind CSS for styling.

      Stitch Design Context:
      ${stitchDesignContext}

      Requirements:
      - Create a file named 'HeroSection.tsx'.
      - Implement the design exactly as described using Tailwind CSS classes.
      - Ensure the code is production-ready and fully functional.
      `,
    });

    console.log(`Session created! ID: ${session.id}`);
    console.log('Waiting for the agent to process the design and generate the code...');

    // 2. Await the final outcome of the session
    const outcome = await session.result();

    console.log('\n--- Session Result ---');
    console.log(`State: ${outcome.state}`);

    if (outcome.state === 'completed') {
      // 3. Extract the generated React component
      const files = outcome.generatedFiles();
      const heroComponentFile = files.get('HeroSection.tsx');

      if (heroComponentFile) {
        console.log('\nSuccessfully generated the React component from the Stitch design:');
        console.log('--------------------------------------------------');
        console.log(heroComponentFile.content);
        console.log('--------------------------------------------------');
        console.log('\nYou can now integrate this file into your web application project.');
      } else {
        console.log('\nThe agent completed the task, but the expected "HeroSection.tsx" file was not found.');

        if (files.size > 0) {
            console.log('\nGenerated Files instead:');
            for (const [filename, content] of files.entries()) {
                console.log(`\nFile: ${filename}`);
                console.log(content.content);
            }
        }
      }
    } else {
      console.error('The session did not complete successfully. Please review the logs.');
    }

  } catch (error) {
    console.error('An error occurred during the session:', error);
  }
}

// Run the example
main();
