import { jules } from '@google/jules-sdk';
import { stitch } from '@google/stitch-sdk';

/**
 * Stitch Integration Example
 *
 * This example demonstrates how to integrate a website design generated by Stitch
 * into an existing codebase using Jules.
 *
 * It uses the @google/stitch-sdk to generate a real design, gets the HTML download
 * URL, and asks Jules to apply the design updates to a specific repository.
 */
async function main() {
  // Check for API keys
  if (!process.env.JULES_API_KEY) {
    console.error('Error: JULES_API_KEY environment variable is not set.');
    console.error('Please set it using: export JULES_API_KEY="your-api-key"');
    process.exit(1);
  }

  if (!process.env.STITCH_API_KEY) {
    console.error('Error: STITCH_API_KEY environment variable is not set.');
    console.error('Please set it using: export STITCH_API_KEY="your-api-key"');
    process.exit(1);
  }

  // --- Configuration ---
  // Replace these with a real repository and branch you own for testing.
  const GITHUB_REPO = process.env.GITHUB_REPO || 'davideast/dataprompt';
  const BASE_BRANCH = process.env.BASE_BRANCH || 'main';

  const targetComponent = 'Hero Section';

  console.log('--- Jules + Stitch Integration ---');
  console.log(`Target Repo: ${GITHUB_REPO} (${BASE_BRANCH})`);
  console.log(`Target Component: ${targetComponent}`);
  console.log('----------------------------------\n');

  try {
    // 1. Generate a design with Stitch
    console.log('Generating design with Stitch...');
    const project = await stitch.createProject('Jules Integration Example');
    const screen = await project.generate('A hero section with a dark theme, a large title, a subtitle, and a call-to-action button.');

    // Get the HTML download URL for the generated screen
    const stitchUrl = await screen.getHtml();

    console.log(`Stitch Design HTML URL: ${stitchUrl}\n`);

    // 2. Create a session pointing to the target repository
    console.log('Creating session and assigning task to Jules...');

    const session = await jules.session({
      // We pass the prompt explaining what to do
      prompt: `
        You are a frontend developer tasked with integrating a new design.

        **Design Source**
        Please review the updated design components for the ${targetComponent}
        from this Stitch project export:
        ${stitchUrl}

        **Task**
        1. Analyze the structure, styling (CSS/Tailwind/etc.), and logic in the Stitch export.
        2. Locate the existing implementation of the ${targetComponent} in the repository.
        3. Update the existing code to match the new Stitch design.
        4. Ensure any interactive elements (buttons, links) retain their original functionality if not specified otherwise in the design.
        5. Verify that the changes do not break existing tests or builds.
      `,
      // Define the target repository
      source: {
        github: GITHUB_REPO,
        baseBranch: BASE_BRANCH,
      },
      // Automatically create a PR when the agent finishes successfully
      autoPr: true,
    });

    console.log(`\nSession created successfully! Session ID: ${session.id}`);
    console.log('Monitoring agent progress...\n');

    // 3. Stream the agent's progress
    // We observe the activities to keep the user informed.
    // We catch errors from stream() gracefully because the activities endpoint
    // may momentary return 404 immediately after session creation.
    try {
      for await (const activity of session.stream()) {
        switch (activity.type) {
          case 'planGenerated':
            console.log('\n[PLAN GENERATED]');
            activity.plan.steps.forEach((step, index) => {
              console.log(`  ${index + 1}. ${step.title}`);
            });
            break;
          case 'progressUpdated':
            console.log(`[PROGRESS] ${activity.title}`);
            // If the agent creates code changes, we can log a summary
            if (activity.artifacts) {
              for (const artifact of activity.artifacts) {
                if (artifact.type === 'changeSet') {
                  const parsed = artifact.parsed();
                  console.log(`  -> Modified files: ${parsed.files.length}`);
                  for (const file of parsed.files) {
                    console.log(`     - ${file.path} (+${file.additions} -${file.deletions})`);
                  }
                }
              }
            }
            break;
          case 'agentMessaged':
            console.log(`\n[AGENT MESSAGE] ${activity.message}`);
            break;
          case 'sessionCompleted':
            console.log('\n[SESSION COMPLETED]');
            break;
        }
      }
    } catch (streamError) {
       console.log('Encountered error while streaming activities. Waiting for result directly...', streamError);
    }

    // 4. Wait for the final outcome and display results
    const outcome = await session.result();

    console.log('\n--- Final Outcome ---');
    console.log(`State: ${outcome.state}`);

    if (outcome.state === 'completed' && outcome.pullRequest) {
      console.log('Success! The agent has integrated the Stitch design.');
      console.log(`Pull Request URL: ${outcome.pullRequest.url}`);
    } else if (outcome.state === 'completed') {
      console.log('Success! The task is complete, but no PR was created (or autoPr was disabled).');
    } else {
      console.error(`The session failed or ended with state: ${outcome.state}`);
      // Retrieve error information from activities if possible
      const errors = await jules.select({
        from: 'activities',
        where: { type: 'agentMessaged', 'session.id': session.id },
        order: 'desc',
      });
      if (errors.length > 0) {
        console.error('Last message from agent:', errors[0].message);
      }
    }

  } catch (error) {
    console.error('An error occurred while running the example:', error);
  }
}

// Run the example
main();
