import { jules, ChangeSetArtifact } from '@google/jules-sdk';
import type { AnalyzeGitPatchSpec, AnalyzeGitPatchInput, AnalyzeGitPatchResult } from './spec.js';

export class AnalyzeGitPatchHandler implements AnalyzeGitPatchSpec {
  async execute(input: AnalyzeGitPatchInput): Promise<AnalyzeGitPatchResult> {
    try {
      console.log(`Searching recent ${input.limit} activities for a GitPatch...`);

      // 1. Search for a recent session with GitPatch data
      const activitiesWithChanges = await jules.select({
        from: 'activities',
        where: { artifactCount: { gt: 0 } },
        order: 'desc',
        limit: input.limit,
      });

      let gitPatchData: string | null = null;
      let sourceSessionId: string | null = null;

      for (const activity of activitiesWithChanges) {
        if (activity.artifacts) {
          for (const artifact of activity.artifacts) {
            if (artifact.type === 'changeSet') {
              const changeSet = artifact as ChangeSetArtifact;
              if (changeSet.gitPatch?.unidiffPatch) {
                gitPatchData = changeSet.gitPatch.unidiffPatch;
                sourceSessionId = activity.session?.id || 'unknown';
                break;
              }
            }
          }
        }
        if (gitPatchData) break;
      }

      if (!gitPatchData) {
        return {
          success: false,
          error: {
            code: 'NO_GITPATCH_FOUND',
            message: `Could not find any recent GitPatch data in the local cache.`,
            suggestion: 'Run a session that modifies code and generates a changeset first.',
            recoverable: true,
          },
        };
      }

      console.log(`Found GitPatch data from session ${sourceSessionId}.`);
      console.log(`Starting analysis session against ${input.sourceRepo}...`);

      // 2. Run a new session against the same source repository to analyze it
      const session = await jules.session({
        prompt: `You are an expert code reviewer. Analyze the following GitPatch data against the repository context.
        Identify any potential bugs, areas for optimization, or coding standard violations in the changes.
        Explain how the automated code could be improved.
        Write your analysis to a file named 'analysis.md'.

        ## GitPatch Data
        \`\`\`diff
        ${gitPatchData}
        \`\`\`
        `,
        source: { github: input.sourceRepo },
      });

      console.log(`Session created: ${session.id}`);
      console.log('Waiting for the agent to complete the analysis...');

      const outcome = await session.result();

      if (outcome.state === 'failed') {
        return {
          success: false,
          error: {
            code: 'SESSION_FAILED',
            message: `The analysis session failed.`,
            recoverable: false,
          },
        };
      }

      const files = outcome.generatedFiles();
      const analysisFile = files.get('analysis.md');

      if (!analysisFile) {
        return {
          success: false,
          error: {
            code: 'SESSION_FAILED',
            message: `The analysis file was not generated by the agent.`,
            recoverable: true,
          },
        };
      }

      return {
        success: true,
        data: {
          analysis: analysisFile.content,
          sourceSessionId: sourceSessionId || 'unknown',
        },
      };

    } catch (error) {
      return {
        success: false,
        error: {
          code: 'UNKNOWN_ERROR',
          message: error instanceof Error ? error.message : String(error),
          recoverable: false,
        },
      };
    }
  }
}
