import { jules } from '@google/jules-sdk';

/**
 * GitPatch Goals Review Example
 *
 * This example demonstrates how to evaluate an AI agent's output against
 * its original goals and coding standards by extracting the generated code
 * diff (GitPatch) and passing it to a second review session.
 */
async function main() {
  if (!process.env.JULES_API_KEY) {
    console.error('Error: JULES_API_KEY environment variable is missing.');
    process.exit(1);
  }

  console.log('--- Step 1: Initiating Code Generation Session ---');

  const originalPrompt = `
    Create a simple Node.js HTTP server.
    Requirements:
    - Listen on port 8080.
    - Serve a "Hello, World!" plain text response for the root path (/).
    - Return a 404 Not Found for all other paths.
    - Use the built-in 'http' module.
  `;

  // 1. Create the generation session
  const genSession = await jules.session({
    prompt: originalPrompt,
  });

  console.log(`Generation Session created! ID: ${genSession.id}`);
  console.log('Waiting for the agent to generate code...');

  const genOutcome = await genSession.result();

  if (genOutcome.state !== 'completed') {
    console.error(`Generation session failed with state: ${genOutcome.state}`);
    process.exit(1);
  }

  // 2. Extract the GitPatch (diff) of the generated code
  let gitPatch = '';

  // Get activities for the session
  const activities = await jules.select({
      from: 'activities',
      where: { 'session.id': genSession.id },
      order: 'asc',
  });

  for (const activity of activities) {
      if (activity.type === 'progressUpdated' && activity.artifacts) {
          for (const artifact of activity.artifacts) {
             if (artifact.type === 'changeSet') {
                 // The changeSet artifact has a raw content property representing the git diff
                 if (artifact.content) {
                    gitPatch += artifact.content + '\n';
                 }
             }
          }
      }
  }

  if (!gitPatch) {
    console.log('No GitPatch data found in the generation session.');
    // Fallback to getting generated files
    const files = genOutcome.generatedFiles();
    if (files.size > 0) {
      for (const [path, file] of files.entries()) {
        gitPatch += `--- a/${path}\n+++ b/${path}\n@@ -0,0 +1,${file.content.split('\n').length} @@\n`;
        gitPatch +=
          file.content
            .split('\n')
            .map((l) => '+' + l)
            .join('\n') + '\n';
      }
    } else {
      console.error('No generated files found either. Exiting.');
      process.exit(1);
    }
  }

  console.log('\n--- Step 2: Extracted GitPatch ---');
  console.log(gitPatch.substring(0, 500) + '...\n(truncated for brevity)');

  console.log('\n--- Step 3: Initiating Review Session ---');

  const reviewPrompt = `
    You are an expert code reviewer. Review the following GitPatch generated by an AI agent.

    ### Original Goals and Requirements
    ${originalPrompt}

    ### GitPatch to Review
    \`\`\`diff
    ${gitPatch}
    \`\`\`

    ### Task
    1. Determine if the generated code successfully meets ALL the Original Goals and Requirements.
    2. Determine if the code adheres to general Node.js coding standards and best practices.
    3. Provide a clear, structured markdown response with the following sections:
       - **Goal Satisfaction**: Yes/No and why.
       - **Code Quality**: Feedback on best practices.
       - **Final Verdict**: Pass or Fail.
  `;

  // 3. Create the review session
  const reviewSession = await jules.session({
    prompt: reviewPrompt,
  });

  console.log(`Review Session created! ID: ${reviewSession.id}`);
  console.log('Waiting for the agent to review the code...');

  const reviewOutcome = await reviewSession.result();

  console.log('\n--- Step 4: Review Results ---');

  if (reviewOutcome.state === 'completed') {
    // 4. Output the review results
    const reviewActivities = await jules.select({
      from: 'activities',
      where: { type: 'agentMessaged', 'session.id': reviewSession.id },
      order: 'desc',
      limit: 1,
    });

    if (reviewActivities.length > 0) {
      console.log(reviewActivities[0].message);
    } else {
       const files = reviewOutcome.generatedFiles();
       if (files.size > 0) {
           for (const [filename, content] of files.entries()) {
               console.log(`\nReview File: ${filename}`);
               console.log(content.content);
           }
       } else {
           console.log('Review agent did not leave a final message or file.');
       }
    }
  } else {
    console.error(`Review session failed with state: ${reviewOutcome.state}`);
  }
}

main().catch(console.error);
