import { jules, SessionClient, SessionOutcome } from '@google/jules-sdk';

/**
 * Initiates the review session with the extracted GitPatch and original prompt.
 * Streams progress back until completion and returns the final session outcome.
 */
export async function reviewCode(
  originalPrompt: string,
  gitPatch: string
): Promise<SessionOutcome> {
  console.error('\n--- Step 3: Initiating Review Session ---');

  const reviewPrompt = `
You are an expert code reviewer. Review the following GitPatch generated by an AI agent.

### Original Goals and Requirements
${originalPrompt}

### GitPatch to Review
\`\`\`diff
${gitPatch}
\`\`\`

### Task
1. Determine if the generated code successfully meets ALL the Original Goals and Requirements.
2. Determine if the code adheres to general Node.js coding standards and best practices.
3. Provide a clear, structured markdown response with the following sections:
   - **Goal Satisfaction**: Yes/No and why.
   - **Code Quality**: Feedback on best practices.
   - **Final Verdict**: Pass or Fail.
`;

  const session = await jules.session({ prompt: reviewPrompt });

  console.error(`Review Session created! ID: ${session.id}`);
  console.error('Streaming agent progress...\n');

  try {
    for await (const activity of session.stream()) {
      if (activity.type === 'progressUpdated') {
        console.error(`[Review] ${activity.title}`);
      } else if (activity.type === 'agentMessaged') {
        console.error(`[Review Agent]: ${activity.message.substring(0, 100)}...`);
      } else if (activity.type === 'sessionCompleted') {
        console.error('[Review] Session complete.');
      } else if (activity.type === 'sessionFailed') {
        console.error('[Review] Session failed.');
      }
    }
  } catch (err) {
    console.error('[Review] Streaming not available yet. Waiting for completion...');
  }

  const reviewOutcome = await session.result();
  return reviewOutcome;
}
