// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export interface WorkflowTemplateOptions {
  workflowName: string;
  baseBranch: string;
}

/**
 * Build the GitHub Actions workflow YAML for merge conflict detection.
 * Isolated from handler logic so template changes never conflict with
 * file-writing logic changes.
 */
export function buildWorkflowYaml(options: WorkflowTemplateOptions): string {
  return `# Generated by jules-merge init
# This workflow checks for merge conflicts on pull requests.
name: ${options.workflowName}

on:
  pull_request:
    branches: [${options.baseBranch}]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Attempt merge
        id: merge
        continue-on-error: true
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin \${{ github.event.pull_request.base.ref }}
          git merge origin/\${{ github.event.pull_request.base.ref }} --no-commit --no-ff || true

      - name: Check for conflicts
        run: |
          npx @google/jules-merge check-conflicts \\
            --repo \${{ github.repository }} \\
            --pr \${{ github.event.pull_request.number }} \\
            --sha \${{ github.event.pull_request.head.sha }}
`;
}
