// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { WorkflowTemplate } from './types.js';
import { buildCron } from './cron.js';
import { fleetAppEnv, fleetAppSteps, githubTokenExpr } from './auth-snippets.js';

export function buildAnalyzeTemplate(intervalMinutes: number, auth: 'token' | 'app' = 'token'): WorkflowTemplate {
  const cron = buildCron(intervalMinutes);
  return {
    repoPath: '.github/workflows/fleet-analyze.yml',
    content: `\
# Generated by @google/jules-fleet init
# https://github.com/google-labs-code/jules-sdk

name: Fleet Analyze

on:
  schedule:
    - cron: '${cron}'
  workflow_dispatch:
    inputs:
      goal:
        description: 'Path to goal file (or blank for all)'
        type: string
        default: ''
      milestone:
        description: 'Milestone ID override'
        type: string
        default: ''

concurrency:
  group: fleet-analyze
  cancel-in-progress: false

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'${fleetAppSteps(auth)}
      - run: npx -y --package=@google/jules-fleet jules-fleet analyze --goal "\${{ inputs.goal }}" --milestone "\${{ inputs.milestone }}"
        env:
          GITHUB_TOKEN: \${{ ${githubTokenExpr(auth)} }}
          JULES_API_KEY: \${{ secrets.JULES_API_KEY }}${fleetAppEnv(auth)}
`,
  };
}

/** @deprecated Use buildAnalyzeTemplate(360) instead */
export const FLEET_ANALYZE_TEMPLATE: WorkflowTemplate = buildAnalyzeTemplate(360);
