// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { WorkflowTemplate } from './types.js';
import { buildCron, dispatchOffset } from './cron.js';
import { fleetEnvBlock } from './auth-snippets.js';

export function buildDispatchTemplate(intervalMinutes: number): WorkflowTemplate {
  const cron = buildCron(intervalMinutes, dispatchOffset(intervalMinutes));
  return {
    repoPath: '.github/workflows/fleet-dispatch.yml',
    content: `\
# Generated by @google/jules-fleet init
# https://github.com/google-labs-code/jules-sdk

name: Fleet Dispatch

on:
  schedule:
    - cron: '${cron}'
  workflow_dispatch:
    inputs:
      milestone:
        description: 'Milestone ID to dispatch (leave empty to dispatch all)'
        type: string
        required: false

concurrency:
  group: fleet-dispatch
  cancel-in-progress: false

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      milestones: \${{ steps.list.outputs.milestones }}
    steps:
      - name: Resolve milestones
        id: list
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          INPUT_MILESTONE: \${{ inputs.milestone }}
        run: |
          if [ -n "$INPUT_MILESTONE" ]; then
            echo "milestones=[\\"$INPUT_MILESTONE\\"]" >> "$GITHUB_OUTPUT"
          else
            milestones=$(gh api repos/\${{ github.repository }}/milestones --jq '[.[].number | tostring]')
            echo "milestones=$milestones" >> "$GITHUB_OUTPUT"
          fi

  dispatch:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        milestone: \${{ fromJSON(needs.discover.outputs.milestones) }}
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npx -y --package=@google/jules-fleet jules-fleet dispatch --milestone \${{ matrix.milestone }}
        env:${fleetEnvBlock()}
`,
  };
}

/** @deprecated Use buildDispatchTemplate(360) instead */
export const FLEET_DISPATCH_TEMPLATE: WorkflowTemplate = buildDispatchTemplate(360);
