// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { WorkflowTemplate } from './types.js';

export const FLEET_DISPATCH_TEMPLATE: WorkflowTemplate = {
  repoPath: '.github/workflows/fleet-dispatch.yml',
  content: `\
# Generated by @google/jules-fleet init
# https://github.com/google-labs-code/jules-sdk

name: Fleet Dispatch

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 6am UTC — edit to your preference
  workflow_dispatch:
    inputs:
      milestone:
        description: 'Milestone ID to dispatch'
        type: string
        required: true

concurrency:
  group: fleet-dispatch
  cancel-in-progress: false

jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npx @google/jules-fleet dispatch --milestone \${{ inputs.milestone }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          JULES_API_KEY: \${{ secrets.JULES_API_KEY }}
          GITHUB_APP_ID: \${{ secrets.FLEET_APP_ID }}
          GITHUB_APP_PRIVATE_KEY_BASE64: \${{ secrets.FLEET_APP_PRIVATE_KEY }}
          GITHUB_APP_INSTALLATION_ID: \${{ secrets.FLEET_APP_INSTALLATION_ID }}
`,
};
