// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { WorkflowTemplate } from './types.js';
import { buildCron, mergeInterval } from './cron.js';

export function buildMergeTemplate(intervalMinutes: number, auth: 'token' | 'app' = 'token'): WorkflowTemplate {
  const cron = buildCron(mergeInterval(intervalMinutes));
  return {
    repoPath: '.github/workflows/fleet-merge.yml',
    content: `\
# Generated by @google/jules-fleet init
# https://github.com/google-labs-code/jules-sdk

name: Fleet Merge

on:
  schedule:
    - cron: '${cron}'
  workflow_run:
    workflows: ['Conflict Detection']
    types: [completed]
  workflow_dispatch:
    inputs:
      mode:
        description: 'PR selection mode'
        type: choice
        options:
          - label
          - fleet-run
        default: 'label'
      fleet_run_id:
        description: 'Fleet run ID (required for fleet-run mode)'
        type: string
        default: ''
      redispatch:
        description: 'Enable smart conflict resolution'
        type: boolean
        default: true

concurrency:
  group: fleet-merge
  cancel-in-progress: false

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'${auth === 'app' ? `
      - name: Decode private key
        id: decode-key
        run: |
          echo "\${{ secrets.FLEET_APP_PRIVATE_KEY }}" | base64 -d > /tmp/fleet-app-key.pem
          {
            echo "pem<<PEMEOF"
            cat /tmp/fleet-app-key.pem
            echo "PEMEOF"
          } >> "\$GITHUB_OUTPUT"
          rm /tmp/fleet-app-key.pem
      - name: Generate Fleet App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: \${{ secrets.FLEET_APP_ID }}
          private-key: \${{ steps.decode-key.outputs.pem }}` : ''}
      - run: |
          REDISPATCH_FLAG="--redispatch"
          if [ "\${{ inputs.redispatch }}" = "false" ]; then
            REDISPATCH_FLAG=""
          fi
          npx -y --package=@google/jules-fleet jules-fleet merge --mode \${{ inputs.mode || 'label' }} --run-id "\${{ inputs.fleet_run_id }}" \$REDISPATCH_FLAG
        env:
          GITHUB_TOKEN: \${{ ${auth === 'app' ? 'steps.app-token.outputs.token' : 'secrets.GITHUB_TOKEN'} }}
          JULES_API_KEY: \${{ secrets.JULES_API_KEY }}
          FLEET_APP_ID: \${{ secrets.FLEET_APP_ID }}
          FLEET_APP_PRIVATE_KEY: \${{ secrets.FLEET_APP_PRIVATE_KEY }}
          FLEET_APP_INSTALLATION_ID: \${{ secrets.FLEET_APP_INSTALLATION_ID }}
`,
  };
}

/** @deprecated Use buildMergeTemplate(360) instead */
export const FLEET_MERGE_TEMPLATE: WorkflowTemplate = buildMergeTemplate(360);
