// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { WorkflowTemplate } from './types.js';

export const FLEET_MERGE_TEMPLATE: WorkflowTemplate = {
  repoPath: '.github/workflows/fleet-merge.yml',
  content: `\
# Generated by @google/jules-fleet init
# https://github.com/google-labs-code/jules-sdk

name: Fleet Merge

on:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours — edit to your preference
  workflow_dispatch:
    inputs:
      mode:
        description: 'PR selection mode'
        type: choice
        options:
          - label
          - fleet-run
        default: 'label'
      fleet_run_id:
        description: 'Fleet run ID (required for fleet-run mode)'
        type: string
        default: ''
      re_dispatch:
        description: 'Auto re-dispatch on merge conflict'
        type: boolean
        default: true

concurrency:
  group: fleet-merge
  cancel-in-progress: false

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: |
          REDISPATCH_FLAG=""
          if [ "\${{ inputs.re_dispatch }}" = "true" ]; then
            REDISPATCH_FLAG="--re-dispatch"
          fi
          npx @google/jules-fleet merge \\
            --mode \${{ inputs.mode || 'label' }} \\
            --run-id "\${{ inputs.fleet_run_id }}" \\
            \$REDISPATCH_FLAG
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          JULES_API_KEY: \${{ secrets.JULES_API_KEY }}
          GITHUB_APP_ID: \${{ secrets.FLEET_APP_ID }}
          GITHUB_APP_PRIVATE_KEY_BASE64: \${{ secrets.FLEET_APP_PRIVATE_KEY }}
          GITHUB_APP_INSTALLATION_ID: \${{ secrets.FLEET_APP_INSTALLATION_ID }}
`,
};
