/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Schema Introspection for Jules Query Language
 *
 * Provides TypeScript type definitions and field metadata for LLM discoverability.
 * These schemas help LLMs understand the shape of Session, Activity, and related types
 * to translate natural language queries into proper JQL.
 */

/**
 * Field metadata for schema introspection
 */
export interface FieldMeta {
  /** Field name */
  name: string;
  /** TypeScript type representation */
  type: string;
  /** Human-readable description */
  description: string;
  /** Whether field is optional */
  optional?: boolean;
  /** Whether field is computed (not stored, derived at query time) */
  computed?: boolean;
  /** Whether field can be filtered in where clause */
  filterable?: boolean;
  /** Whether field can be used in select projection */
  selectable?: boolean;
  /** Nested fields if this is an object or array type */
  fields?: FieldMeta[];
}

/**
 * Schema definition for a domain
 */
export interface DomainSchema {
  /** Domain name */
  domain: 'sessions' | 'activities';
  /** Human-readable description */
  description: string;
  /** All fields in this domain */
  fields: FieldMeta[];
  /** Example queries for this domain */
  examples: QueryExample[];
}

/**
 * Example query for documentation
 */
export interface QueryExample {
  /** Natural language description */
  description: string;
  /** JQL query */
  query: Record<string, unknown>;
}

/**
 * Schema for SessionResource
 */
export const SESSION_SCHEMA: DomainSchema = {
  domain: 'sessions',
  description:
    'A Jules session representing a task or conversation with the agent',
  fields: [
    {
      name: 'id',
      type: 'string',
      description: 'Unique session identifier',
      filterable: true,
      selectable: true,
    },
    {
      name: 'name',
      type: 'string',
      description: 'Full resource name (e.g., "sessions/314159...")',
      selectable: true,
    },
    {
      name: 'title',
      type: 'string',
      description: 'Human-readable session title',
      filterable: true,
      selectable: true,
    },
    {
      name: 'prompt',
      type: 'string',
      description: 'The initial instruction or task description',
      selectable: true,
    },
    {
      name: 'state',
      type: 'SessionState',
      description:
        'Current session state: "queued" | "planning" | "awaitingPlanApproval" | "awaitingUserFeedback" | "inProgress" | "paused" | "failed" | "completed"',
      filterable: true,
      selectable: true,
    },
    {
      name: 'createTime',
      type: 'string',
      description: 'RFC 3339 timestamp when session was created',
      filterable: true,
      selectable: true,
    },
    {
      name: 'updateTime',
      type: 'string',
      description: 'RFC 3339 timestamp when session was last updated',
      filterable: true,
      selectable: true,
    },
    {
      name: 'url',
      type: 'string',
      description: 'URL to view the session in the Jules web app',
      selectable: true,
    },
    {
      name: 'durationMs',
      type: 'number',
      description: 'Duration in milliseconds (updateTime - createTime)',
      computed: true,
      selectable: true,
    },
    {
      name: 'sourceContext',
      type: 'SourceContext',
      description: 'The source code context (repository, branch)',
      selectable: true,
      fields: [
        {
          name: 'source',
          type: 'string',
          description: 'Source name (e.g., "sources/github/owner/repo")',
          selectable: true,
        },
        {
          name: 'githubRepoContext',
          type: 'object',
          description: 'GitHub-specific context',
          optional: true,
          selectable: true,
          fields: [
            {
              name: 'startingBranch',
              type: 'string',
              description: 'The branch the session started from',
              selectable: true,
            },
          ],
        },
      ],
    },
    {
      name: 'outputs',
      type: 'SessionOutput[]',
      description: 'Outputs generated by the session (e.g., pull requests)',
      selectable: true,
      fields: [
        {
          name: 'type',
          type: '"pullRequest"',
          description: 'Output type discriminator',
          selectable: true,
        },
        {
          name: 'pullRequest',
          type: 'PullRequest',
          description: 'Pull request details',
          selectable: true,
          fields: [
            {
              name: 'url',
              type: 'string',
              description: 'PR URL',
              selectable: true,
            },
            {
              name: 'title',
              type: 'string',
              description: 'PR title',
              selectable: true,
            },
            {
              name: 'description',
              type: 'string',
              description: 'PR description',
              selectable: true,
            },
          ],
        },
      ],
    },
    {
      name: 'outcome',
      type: 'object',
      description: 'Final outcome if session is in terminal state',
      optional: true,
      selectable: true,
      fields: [
        {
          name: 'status',
          type: '"SUCCESS" | "FAILURE"',
          description: 'Outcome status',
          selectable: true,
        },
        {
          name: 'summary',
          type: 'string',
          description: 'Human-readable outcome summary',
          selectable: true,
        },
      ],
    },
  ],
  examples: [
    {
      description: 'Get all completed sessions',
      query: {
        from: 'sessions',
        where: { state: 'completed' },
        select: ['id', 'title', 'createTime'],
      },
    },
    {
      description: 'Find sessions with PR output',
      query: {
        from: 'sessions',
        where: { 'outputs.type': 'pullRequest' },
        select: ['id', 'title', 'outputs.pullRequest.url'],
      },
    },
    {
      description: 'Get session with all activities',
      query: {
        from: 'sessions',
        where: { id: 'SESSION_ID' },
        include: { activities: true },
      },
    },
  ],
};

/**
 * Schema for Activity types
 */
export const ACTIVITY_SCHEMA: DomainSchema = {
  domain: 'activities',
  description: 'An event or action within a session',
  fields: [
    {
      name: 'id',
      type: 'string',
      description: 'Unique activity identifier',
      filterable: true,
      selectable: true,
    },
    {
      name: 'name',
      type: 'string',
      description: 'Full resource name',
      selectable: true,
    },
    {
      name: 'type',
      type: 'ActivityType',
      description:
        'Activity type: "agentMessaged" | "userMessaged" | "planGenerated" | "planApproved" | "progressUpdated" | "sessionCompleted" | "sessionFailed"',
      filterable: true,
      selectable: true,
    },
    {
      name: 'createTime',
      type: 'string',
      description: 'RFC 3339 timestamp when activity was created',
      filterable: true,
      selectable: true,
    },
    {
      name: 'originator',
      type: '"user" | "agent" | "system"',
      description: 'Entity that originated this activity',
      filterable: true,
      selectable: true,
    },
    {
      name: 'sessionId',
      type: 'string',
      description: 'ID of the parent session',
      filterable: true,
      selectable: true,
    },
    {
      name: 'artifactCount',
      type: 'number',
      description: 'Number of artifacts in this activity',
      computed: true,
      selectable: true,
    },
    {
      name: 'summary',
      type: 'string',
      description: 'Human-readable summary of the activity',
      computed: true,
      selectable: true,
    },
    // Type-specific fields
    {
      name: 'message',
      type: 'string',
      description: 'Message content (for agentMessaged, userMessaged)',
      optional: true,
      selectable: true,
    },
    {
      name: 'plan',
      type: 'Plan',
      description: 'Generated plan (for planGenerated)',
      optional: true,
      selectable: true,
      fields: [
        {
          name: 'id',
          type: 'string',
          description: 'Plan ID',
          selectable: true,
        },
        {
          name: 'createTime',
          type: 'string',
          description: 'Plan creation time',
          selectable: true,
        },
        {
          name: 'steps',
          type: 'PlanStep[]',
          description: 'Plan steps',
          selectable: true,
          fields: [
            {
              name: 'id',
              type: 'string',
              description: 'Step ID',
              selectable: true,
            },
            {
              name: 'title',
              type: 'string',
              description: 'Step title',
              selectable: true,
            },
            {
              name: 'description',
              type: 'string',
              description: 'Step description',
              optional: true,
              selectable: true,
            },
            {
              name: 'index',
              type: 'number',
              description: 'Step index',
              selectable: true,
            },
          ],
        },
      ],
    },
    {
      name: 'planId',
      type: 'string',
      description: 'ID of approved plan (for planApproved)',
      optional: true,
      selectable: true,
    },
    {
      name: 'title',
      type: 'string',
      description: 'Progress title (for progressUpdated)',
      optional: true,
      selectable: true,
    },
    {
      name: 'description',
      type: 'string',
      description: 'Progress description (for progressUpdated)',
      optional: true,
      selectable: true,
    },
    {
      name: 'reason',
      type: 'string',
      description: 'Failure reason (for sessionFailed)',
      optional: true,
      selectable: true,
    },
    {
      name: 'artifacts',
      type: 'Artifact[]',
      description: 'Artifacts produced by this activity',
      selectable: true,
      fields: [
        {
          name: 'type',
          type: '"changeSet" | "media" | "bashOutput"',
          description: 'Artifact type discriminator',
          filterable: true,
          selectable: true,
        },
        {
          name: 'changeSet',
          type: 'ChangeSet',
          description: 'Code changes (for changeSet type)',
          optional: true,
          selectable: true,
          fields: [
            {
              name: 'source',
              type: 'string',
              description: 'Source name',
              selectable: true,
            },
            {
              name: 'gitPatch',
              type: 'GitPatch',
              description: 'Git patch data',
              selectable: true,
              fields: [
                {
                  name: 'unidiffPatch',
                  type: 'string',
                  description: 'Unidiff patch content',
                  selectable: true,
                },
                {
                  name: 'baseCommitId',
                  type: 'string',
                  description: 'Base commit SHA',
                  selectable: true,
                },
                {
                  name: 'suggestedCommitMessage',
                  type: 'string',
                  description: 'Suggested commit message',
                  selectable: true,
                },
              ],
            },
          ],
        },
        {
          name: 'command',
          type: 'string',
          description: 'Bash command executed (for bashOutput type)',
          optional: true,
          filterable: true,
          selectable: true,
        },
        {
          name: 'stdout',
          type: 'string',
          description: 'Standard output (for bashOutput type)',
          optional: true,
          selectable: true,
        },
        {
          name: 'stderr',
          type: 'string',
          description: 'Standard error (for bashOutput type)',
          optional: true,
          selectable: true,
        },
        {
          name: 'exitCode',
          type: 'number | null',
          description: 'Exit code (for bashOutput type)',
          optional: true,
          filterable: true,
          selectable: true,
        },
        {
          name: 'data',
          type: 'string',
          description:
            'Base64 media data (for media type) - typically excluded',
          optional: true,
          selectable: true,
        },
        {
          name: 'format',
          type: 'string',
          description: 'Media format (for media type)',
          optional: true,
          selectable: true,
        },
      ],
    },
  ],
  examples: [
    {
      description: 'Get all plan generations from a session',
      query: {
        from: 'activities',
        where: { sessionId: 'SESSION_ID', type: 'planGenerated' },
        select: ['id', 'createTime', 'plan.steps.title'],
      },
    },
    {
      description: 'Find activities with bash commands that failed',
      query: {
        from: 'activities',
        where: {
          'artifacts.type': 'bashOutput',
          'artifacts.exitCode': { neq: 0 },
        },
        select: [
          'id',
          'artifacts.command',
          'artifacts.exitCode',
          'artifacts.stderr',
        ],
      },
    },
    {
      description: 'Get agent messages with their artifacts',
      query: {
        from: 'activities',
        where: { type: 'agentMessaged' },
        select: ['id', 'message', 'artifactCount', 'artifacts.type'],
      },
    },
    {
      description: 'Find activities with code changes',
      query: {
        from: 'activities',
        where: { 'artifacts.type': 'changeSet' },
        select: [
          'id',
          'createTime',
          'artifacts.changeSet.gitPatch.suggestedCommitMessage',
        ],
      },
    },
  ],
};

/**
 * FilterOp schema for where clause operators
 */
export const FILTER_OP_SCHEMA = {
  description: 'Filter operators for where clause',
  operators: [
    {
      name: 'eq',
      description: 'Equals (also supports direct value)',
      example: '{ id: "abc" } or { id: { eq: "abc" } }',
    },
    {
      name: 'neq',
      description: 'Not equals',
      example: '{ state: { neq: "failed" } }',
    },
    {
      name: 'contains',
      description: 'Case-insensitive substring match',
      example: '{ title: { contains: "bug" } }',
    },
    {
      name: 'gt',
      description: 'Greater than',
      example: '{ createTime: { gt: "2024-01-01" } }',
    },
    {
      name: 'lt',
      description: 'Less than',
      example: '{ createTime: { lt: "2024-12-31" } }',
    },
    {
      name: 'gte',
      description: 'Greater than or equal',
      example: '{ artifactCount: { gte: 1 } }',
    },
    {
      name: 'lte',
      description: 'Less than or equal',
      example: '{ artifactCount: { lte: 10 } }',
    },
    {
      name: 'in',
      description: 'Value in array',
      example: '{ state: { in: ["completed", "failed"] } }',
    },
    {
      name: 'exists',
      description: 'Field existence check',
      example: '{ "outputs.pullRequest": { exists: true } }',
    },
  ],
  dotNotation: {
    description:
      'Use dot notation for nested field paths. When filtering arrays, uses existential matching (ANY element matches).',
    examples: [
      '"artifacts.type": "bashOutput"',
      '"artifacts.exitCode": { neq: 0 }',
      '"plan.steps.title": { contains: "test" }',
      '"outputs.pullRequest.url": { exists: true }',
    ],
  },
};

/**
 * Projection schema for select clause
 */
export const PROJECTION_SCHEMA = {
  description: 'Select clause projection syntax',
  syntax: [
    {
      name: 'Field selection',
      description: 'Include specific fields',
      example: '["id", "title", "state"]',
    },
    {
      name: 'Dot notation',
      description: 'Select nested fields',
      example: '["id", "artifacts.type", "artifacts.command"]',
    },
    {
      name: 'Wildcard',
      description: 'Include all fields',
      example: '["*"]',
    },
    {
      name: 'Exclusion',
      description: 'Exclude specific fields (use with wildcard)',
      example: '["*", "-artifacts.data"]',
    },
  ],
  defaults: {
    sessions: ['id', 'state', 'title', 'createTime'],
    activities: [
      'id',
      'type',
      'createTime',
      'originator',
      'artifactCount',
      'summary',
    ],
  },
};

/**
 * Get the full schema for a domain
 */
export function getSchema(domain: 'sessions' | 'activities'): DomainSchema {
  return domain === 'sessions' ? SESSION_SCHEMA : ACTIVITY_SCHEMA;
}

/**
 * Get all schemas with filter and projection documentation
 */
export function getAllSchemas(): {
  sessions: DomainSchema;
  activities: DomainSchema;
  filterOps: typeof FILTER_OP_SCHEMA;
  projection: typeof PROJECTION_SCHEMA;
} {
  return {
    sessions: SESSION_SCHEMA,
    activities: ACTIVITY_SCHEMA,
    filterOps: FILTER_OP_SCHEMA,
    projection: PROJECTION_SCHEMA,
  };
}

/**
 * Generate TypeScript type definition string for a domain
 */
export function generateTypeDefinition(
  domain: 'sessions' | 'activities',
): string {
  const schema = getSchema(domain);
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * ${schema.description}`);
  lines.push(` */`);

  const typeName = domain === 'sessions' ? 'SessionResource' : 'Activity';
  lines.push(`interface ${typeName} {`);

  for (const field of schema.fields) {
    const optional = field.optional ? '?' : '';
    const computed = field.computed ? ' // computed' : '';
    lines.push(`  /** ${field.description} */`);
    lines.push(`  ${field.name}${optional}: ${field.type};${computed}`);
  }

  lines.push(`}`);

  return lines.join('\n');
}

/**
 * Generate markdown documentation for LLM consumption
 */
export function generateMarkdownDocs(): string {
  const lines: string[] = [];

  lines.push('# Jules Query Language (JQL) Schema Reference\n');

  // Sessions
  lines.push('## Sessions Domain\n');
  lines.push(SESSION_SCHEMA.description + '\n');
  lines.push('### Fields\n');
  lines.push('| Field | Type | Description | Filterable |');
  lines.push('|-------|------|-------------|------------|');
  for (const field of SESSION_SCHEMA.fields) {
    const filterable = field.filterable ? 'Yes' : 'No';
    const computed = field.computed ? ' (computed)' : '';
    lines.push(
      `| ${field.name} | ${field.type}${computed} | ${field.description} | ${filterable} |`,
    );
  }

  // Activities
  lines.push('\n## Activities Domain\n');
  lines.push(ACTIVITY_SCHEMA.description + '\n');
  lines.push('### Fields\n');
  lines.push('| Field | Type | Description | Filterable |');
  lines.push('|-------|------|-------------|------------|');
  for (const field of ACTIVITY_SCHEMA.fields) {
    const filterable = field.filterable ? 'Yes' : 'No';
    const computed = field.computed ? ' (computed)' : '';
    lines.push(
      `| ${field.name} | ${field.type}${computed} | ${field.description} | ${filterable} |`,
    );
  }

  // Filter Operators
  lines.push('\n## Filter Operators\n');
  for (const op of FILTER_OP_SCHEMA.operators) {
    lines.push(`- **${op.name}**: ${op.description}`);
    lines.push(`  - Example: \`${op.example}\``);
  }

  // Dot Notation
  lines.push('\n### Dot Notation\n');
  lines.push(FILTER_OP_SCHEMA.dotNotation.description + '\n');
  lines.push('Examples:');
  for (const ex of FILTER_OP_SCHEMA.dotNotation.examples) {
    lines.push(`- \`${ex}\``);
  }

  // Projection
  lines.push('\n## Projection (Select)\n');
  for (const syntax of PROJECTION_SCHEMA.syntax) {
    lines.push(`- **${syntax.name}**: ${syntax.description}`);
    lines.push(`  - Example: \`${syntax.example}\``);
  }

  // Examples
  lines.push('\n## Query Examples\n');
  lines.push('### Sessions');
  for (const ex of SESSION_SCHEMA.examples) {
    lines.push(`\n**${ex.description}**`);
    lines.push('```json');
    lines.push(JSON.stringify(ex.query, null, 2));
    lines.push('```');
  }

  lines.push('\n### Activities');
  for (const ex of ACTIVITY_SCHEMA.examples) {
    lines.push(`\n**${ex.description}**`);
    lines.push('```json');
    lines.push(JSON.stringify(ex.query, null, 2));
    lines.push('```');
  }

  return lines.join('\n');
}
