// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import fs from 'fs';
import path from 'path';
import { z } from 'zod';

// ── Schema ─────────────────────────────────────────────────────────

export const InitInputSchema = z.object({
  base: z.string().default('main'),
  dryRun: z.boolean().default(true),
  force: z.boolean().default(false),
  /** Override CWD for file writing (used in tests). */
  outDir: z.string().optional(),
});

export const InitOutputSchema = z.object({
  status: z.enum(['created', 'dry-run']),
  path: z.string(),
  base: z.string(),
  yaml: z.string().optional(),
});

export type InitInput = z.infer<typeof InitInputSchema>;
export type InitOutput = z.infer<typeof InitOutputSchema>;

// ── Constants ──────────────────────────────────────────────────────

const WORKFLOW_REL_PATH = '.github/workflows/jules-merge-scan.yml';

// ── YAML Builder ───────────────────────────────────────────────────

export function buildWorkflowYaml(baseBranch: string): string {
  return `# Generated by @google/jules-merge init
# Scans PRs for overlapping file changes across parallel agents.
name: Conflict Detection

on:
  pull_request:
    branches: [${baseBranch}]

permissions:
  contents: read
  pull-requests: read

jobs:
  scan-overlaps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for overlapping changes
        run: |
          npx -y --package=@google/jules-merge jules-merge scan --json '{"prs":[\${{ github.event.pull_request.number }}],"repo":"\${{ github.repository }}","base":"\${{ github.event.pull_request.base.ref }}"}'
`;
}

// ── Handler ────────────────────────────────────────────────────────

export function initHandler(rawInput: any): InitOutput {
  const input = InitInputSchema.parse(rawInput);
  const yaml = buildWorkflowYaml(input.base);

  if (input.dryRun) {
    return {
      status: 'dry-run',
      path: WORKFLOW_REL_PATH,
      base: input.base,
      yaml,
    };
  }

  const root = input.outDir || process.cwd();
  const fullPath = path.resolve(root, WORKFLOW_REL_PATH);

  if (fs.existsSync(fullPath) && !input.force) {
    throw new Error(
      `${WORKFLOW_REL_PATH} already exists. Use --force or { "force": true } to overwrite.`,
    );
  }

  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(fullPath, yaml, 'utf-8');

  return {
    status: 'created',
    path: WORKFLOW_REL_PATH,
    base: input.base,
  };
}
